blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/orgs/heyform/discussions/new?category=ideas
    about: Request a feature to be added to the project
  - name: Self hosting questions
    url: https://github.com/orgs/heyform/discussions/new?category=self-hosting
    about: Ask questions and discuss running HeyForm with community members
